### ISSUE TITLE
Web (in-browser) setup, future plans

### ISSUE THREAD

**Issue by IS2511** [mmattbtw/TwitchTunes#10]
list:

- [ ] Web setup
- [ ] Make a TwitchTunes GUI (for local usage)
- [ ] Package TwitchTunes into a GUI

Interactive setup can be made more interactive with a web page. You can temporarily bring up a local web server and down it after setup finishes (if port busy, fallback to console setup)

An even easier setup for user, with GUI and etc. The web page probably would only require the user to input bot username (if no bot their username), login to Spotify and login to Twitch (bot/streamer). Sounds pretty user-friendly

Definitely not a priority issue, not even required. But would make this more accessible to users and look more professional.

Also would bring you closer to the next step: entirely server-side service, because users don't want to download and setup things sadly. The only "user-friendly" alternative is a single .exe (btw python apps can be packed to an exe afaik) with a config somewhere like `AppData/Local`.
This is all IMO, so it can be entirely invalid for you, think yourself, ask around, google, maybe there is a better method/solution

**Comment by IS2511** [comment]
Does it need a GUI though? Maybe a web setup is just fine?
If you do make a GUI, at least make it hide to tray idk

**Comment by mmattbtw** [comment]
@IS2511 The plan with the GUI would be stuff like enabling / disabling sub only mode, and other config stuff.

Just a simple UI using Tkinter, nothing big, and it will be farther into the future

**Comment by mmattbtw** [comment]
Closing because I have seperated this issue into multiple issues. #13, #14, #15
